from enum import Enum

class EventTypes(Enum):
    SNAPSHOT_REQUESTED = "SNAPSHOT_REQUESTED"
    SNAPSHOT_STATE_PROVIDED = "SNAPSHOT_STATE_PROVIDED"
    SNAPSHOT_COMMIT_SIGNAL = "SNAPSHOT_COMMIT_SIGNAL"
    SNAPSHOT_ABORT_SIGNAL = "SNAPSHOT_ABORT_SIGNAL"
    SERVICE_STATE_UPDATED = "SERVICE_STATE_UPDATED"
    GLOBAL_SNAPSHOT_SAVED = "GLOBAL_SNAPSHOT_SAVED"
