# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nexus.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bnexus.proto\x12\x05nexus\"\x8b\x01\n\x0eMetricsRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x33\n\x07metrics\x18\x02 \x03(\x0b\x32\".nexus.MetricsRequest.MetricsEntry\x1a.\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\"\n\x0fMetricsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32O\n\x0cNexusService\x12?\n\x0ePublishMetrics\x12\x15.nexus.MetricsRequest\x1a\x16.nexus.MetricsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nexus_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _METRICSREQUEST_METRICSENTRY._options = None
  _METRICSREQUEST_METRICSENTRY._serialized_options = b'8\001'
  _globals['_METRICSREQUEST']._serialized_start=23
  _globals['_METRICSREQUEST']._serialized_end=162
  _globals['_METRICSREQUEST_METRICSENTRY']._serialized_start=116
  _globals['_METRICSREQUEST_METRICSENTRY']._serialized_end=162
  _globals['_METRICSRESPONSE']._serialized_start=164
  _globals['_METRICSRESPONSE']._serialized_end=198
  _globals['_NEXUSSERVICE']._serialized_start=200
  _globals['_NEXUSSERVICE']._serialized_end=279
# @@protoc_insertion_point(module_scope)
