# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import nexus_pb2 as nexus__pb2


class NexusServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishMetrics = channel.unary_unary(
                '/nexus.NexusService/PublishMetrics',
                request_serializer=nexus__pb2.MetricsRequest.SerializeToString,
                response_deserializer=nexus__pb2.MetricsResponse.FromString,
                )


class NexusServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PublishMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NexusServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishMetrics,
                    request_deserializer=nexus__pb2.MetricsRequest.FromString,
                    response_serializer=nexus__pb2.MetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nexus.NexusService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NexusService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PublishMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nexus.NexusService/PublishMetrics',
            nexus__pb2.MetricsRequest.SerializeToString,
            nexus__pb2.MetricsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
