name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint code
        run: |
          source .venv/bin/activate
          flake8 .

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest --asyncio-mode=auto tests/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 192.168.0.95 >> ~/.ssh/known_hosts
          rsync -avz --exclude '.venv' --exclude '.git' . aiseed@192.168.0.95:/home/aiseed/AIseed
          ssh aiseed@192.168.0.95 "bash /home/aiseed/AIseed/startup.sh"
